function game(data) {
  return {
    rating: 4.0,
    story: "medium",
    intensity: "medium",
    pace: "balanced",
    mood: "action",
    teamwork: "medium",
    tags: [],
    details: [],
    ...data,
    cover: data.cover || `https://cdn.cloudflare.steamstatic.com/steam/apps/${data.appId}/library_hero.jpg`,
    storeUrl: data.storeUrl || `https://store.steampowered.com/app/${data.appId}/`,
    trailerQuery: data.trailerQuery || `${data.title} official trailer`,
    gameplayQuery: data.gameplayQuery || `${data.title} co-op gameplay`
  };
}

const games = [
  game({ title:"Dying Light: The Beast", appId:"3008130", genre:"Open-World Zombie Action", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:59.99,gbp:54.99}, rating:4.4, intensity:"high", story:"high", pace:"open", mood:"zombie", teamwork:"high", vibe:"Open-world parkour, infected, survival action", description:"A darker Dying Light spin-off focused on brutal zombie action, parkour, survival tension, and co-op exploration.", whyPlay:"Your #1 pick if the group wants modern zombie action, parkour movement, horror pressure, and a campaign-style co-op night.", details:["Open-world zombie action","Parkour traversal","Co-op-focused sessions"], tags:["4 players","zombies","open world","parkour","story"] }),
  game({ title:"Tom Clancy's The Division 2", appId:"2221490", genre:"Online Tactical RPG Shooter", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:29.99,gbp:24.99}, rating:4.3, intensity:"high", story:"medium", pace:"open", mood:"military", teamwork:"high", vibe:"Washington DC, loot, cover shooting, builds", description:"A tactical online RPG shooter with strong co-op progression, loot builds, missions, raids, and open-world activities.", whyPlay:"A great fit if your squad wants long-term progression, tactical cover shooting, loot, and missions that reward coordinated builds.", details:["Four-player missions","Loot and build progression","Endgame activities and raids"], tags:["4 players","looter shooter","tactical","open world","builds"] }),
  game({ title:"Destiny 2", appId:"1085660", genre:"Online Looter Shooter", players:"6", platforms:"PC, PlayStation, Xbox", price:{eur:0,gbp:0}, rating:4.2, intensity:"high", story:"high", pace:"fast", mood:"sci-fi", teamwork:"high", vibe:"Space magic, raids, strikes, loot, live service", description:"A huge online sci-fi shooter with strikes, dungeons, raids, seasonal content, builds, and highly polished gunplay.", whyPlay:"Pick this if your group wants a long-term co-op game with raids, buildcrafting, big worlds, and some of the best-feeling shooting around.", details:["Free-to-play entry","Three-player strikes and dungeons","Six-player raids"], tags:["6 players","sci-fi","loot","raids","shooter"] }),
  game({ title:"Borderlands 4", appId:"1285190", genre:"Looter Shooter", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:69.99,gbp:59.99}, rating:4.3, intensity:"high", story:"medium", pace:"fast", mood:"chaotic", teamwork:"medium", vibe:"Loot, chaos, guns, co-op campaign", description:"A new Borderlands entry built around loud co-op shooting, loot, classes, and chaotic campaign action.", whyPlay:"A top pick if you mainly want weapons, jokes, bosses, class skills, and a full co-op looter-shooter campaign.", details:["Four-player co-op","Class-based action","Huge weapon chase"], tags:["4 players","loot","shooter","comedy","campaign"] }),
  game({ title:"FINAL FANTASY XIV Online", appId:"39210", genre:"MMORPG", players:"8", platforms:"PC, PlayStation, Xbox", price:{eur:9.99,gbp:7.99}, rating:4.8, intensity:"medium", story:"high", pace:"tactical", mood:"fantasy", teamwork:"high", vibe:"MMO story, dungeons, raids, jobs, community", description:"A story-heavy MMORPG with co-op dungeons, trials, raids, jobs, crafting, and one of the strongest narratives in the genre.", whyPlay:"The best choice on this list if your group wants a long-term shared RPG with story, raids, dungeons, and hundreds of hours of progression.", details:["Four-player dungeons","Eight-player trials and raids","Massive story campaign"], tags:["8 players","MMO","fantasy","story","raids"] }),
  game({ title:"Borderlands 3", appId:"397540", genre:"Looter Shooter", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:59.99,gbp:49.99}, rating:4.3, intensity:"high", pace:"fast", mood:"chaotic", vibe:"Loot, comedy, chaos, builds", description:"A loud four-player looter shooter packed with guns, skills, bosses, and chaotic campaign co-op.", whyPlay:"Perfect if your group wants constant loot, silly dialogue, explosive combat, and flexible builds.", details:["Four-player campaign co-op","Huge weapon variety","Strong build variety"], tags:["4 players","loot","shooter","comedy","chaos"] }),
  game({ title:"It Takes Two", appId:"1426210", genre:"Co-op Adventure", players:"2", platforms:"PC, PlayStation, Xbox, Switch", price:{eur:39.99,gbp:34.99}, rating:4.8, intensity:"light", story:"high", pace:"balanced", mood:"adventure", teamwork:"high", vibe:"Creative two-player adventure, comedy, emotional story", description:"A must-play two-player adventure built completely around cooperation, variety, and constant surprises.", whyPlay:"Best for duos who want a full co-op journey with story, humor, platforming, puzzles, and some of the most creative teamwork in gaming.", details:["Designed only for two players","Friend's Pass support","Very high variety from chapter to chapter"], tags:["2 players","story","puzzle","platforming","couch co-op"] }),
  game({ title:"A Way Out", appId:"1222700", genre:"Story Adventure", players:"2", platforms:"PC, PlayStation, Xbox", price:{eur:29.99,gbp:24.99}, rating:4.4, intensity:"light", story:"high", pace:"balanced", mood:"crime", teamwork:"high", vibe:"Prison escape, drama, split-screen storytelling", description:"A cinematic two-player crime story where both players experience different parts of the same scenes.", whyPlay:"Great if your duo wants a movie-like co-op night with drama, stealth, chases, and strong narrative focus.", details:["Two-player only","Cinematic split-screen presentation","Short and memorable campaign"], tags:["2 players","story","crime","cinematic","adventure"] }),
  game({ title:"Remnant II", appId:"1282100", genre:"Soulslike Shooter", players:"3", platforms:"PC, PlayStation, Xbox", price:{eur:49.99,gbp:44.99}, rating:4.6, intensity:"hard", pace:"tactical", mood:"dark fantasy", teamwork:"high", vibe:"Bosses, guns, worlds, secrets", description:"A tough co-op shooter with boss fights, procedural worlds, secrets, and excellent three-player synergy.", whyPlay:"One of the best choices for a group that wants challenge, action, builds, and replayable boss-heavy missions.", details:["Three-player co-op","Great boss design","Strong replay value"], tags:["3 players","bosses","shooter","soulslike","builds"] }),
  game({ title:"Deep Rock Galactic", appId:"548430", genre:"Co-op Shooter", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:29.99,gbp:24.99}, rating:4.8, story:"light", pace:"balanced", mood:"sci-fi", teamwork:"high", gamePassPc:"included", vibe:"Dwarves, mining, bugs, missions", description:"A brilliant four-player mission game about space dwarves, mining, bug swarms, classes, and teamwork.", whyPlay:"It is one of the safest co-op recommendations because every class matters and every mission creates stories.", details:["Four distinct classes","Procedural caves","Excellent teamwork"], tags:["4 players","shooter","teamwork","missions","sci-fi"] }),
  game({ title:"Helldivers 2", appId:"553850", genre:"Co-op Shooter", players:"4", platforms:"PC, PlayStation", price:{eur:39.99,gbp:34.99}, rating:4.5, intensity:"high", pace:"fast", mood:"sci-fi", teamwork:"high", vibe:"Friendly fire, chaos, extraction missions", description:"A chaotic squad shooter built around objectives, stratagems, friendly fire, and cinematic last-second extractions.", whyPlay:"Great for squads that want hilarious disasters, tactical pressure, and explosive objective-based co-op.", details:["Four-player online co-op","Objective-based missions","Friendly fire chaos"], tags:["4 players","shooter","sci-fi","chaos","missions"] }),
  game({ title:"Monster Hunter: World", appId:"582010", genre:"Action RPG", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:29.99,gbp:24.99}, rating:4.7, intensity:"hard", pace:"tactical", mood:"fantasy", teamwork:"high", vibe:"Hunts, giant monsters, gear crafting", description:"A deep hunting action RPG where squads track huge monsters, learn patterns, and craft gear from victories.", whyPlay:"Perfect for groups that want long-term progression and memorable boss-like monster hunts.", details:["Four-player hunts","Deep gear crafting","Huge monster roster"], tags:["4 players","bosses","crafting","action RPG","hunts"] }),
  game({ title:"Baldur's Gate 3", appId:"1086940", genre:"Co-op RPG", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:59.99,gbp:49.99}, rating:4.9, intensity:"medium", story:"high", pace:"tactical", mood:"fantasy", teamwork:"medium", vibe:"Choices, characters, tactical combat", description:"A huge story-rich RPG with four-player co-op, tactical combat, companions, and absurd player freedom.", whyPlay:"The best choice when your group wants decisions, roleplay, memorable characters, and long-form campaign chaos.", details:["Four-player campaign","Huge player freedom","Excellent writing"], tags:["4 players","RPG","story","fantasy","choices"] }),
  game({ title:"Sea of Thieves", appId:"1172620", genre:"Pirate Sandbox", players:"4", platforms:"PC, Xbox, PlayStation", price:{eur:39.99,gbp:34.99}, rating:4.3, story:"medium", pace:"open", mood:"adventure", teamwork:"high", gamePassPc:"included", vibe:"Pirates, ships, treasure, stories", description:"A pirate sandbox where crews sail, fight, steal treasure, complete voyages, and create their own stories.", whyPlay:"Great for a group that wants adventures, ship teamwork, unpredictable encounters, and a lighter social vibe.", details:["Crew-based sailing","Open sandbox adventures","Great emergent moments"], tags:["4 players","pirates","sandbox","open world","adventure"] }),
  game({ title:"Grounded", appId:"962130", genre:"Survival Adventure", players:"4", platforms:"PC, Xbox, PlayStation, Switch", price:{eur:39.99,gbp:34.99}, rating:4.4, intensity:"medium", pace:"open", mood:"survival", teamwork:"high", gamePassPc:"included", vibe:"Tiny survival, backyard, crafting", description:"A polished survival adventure where shrunken players build, explore, craft, and survive a dangerous backyard.", whyPlay:"A strong long-term co-op pick if your group likes survival systems but still wants charm and progression.", details:["Four-player survival co-op","Base building","Story progression"], tags:["4 players","survival","crafting","open world","story"] }),
  game({ title:"Halo: The Master Chief Collection", appId:"976730", genre:"Sci-Fi Shooter", players:"4", platforms:"PC, Xbox", price:{eur:39.99,gbp:29.99}, rating:4.7, intensity:"medium", story:"high", pace:"balanced", mood:"sci-fi", teamwork:"medium", gamePassPc:"included", vibe:"Classic campaigns, sci-fi, split-screen legacy", description:"A massive collection of classic Halo campaigns and multiplayer content with strong co-op story value.", whyPlay:"Great for squads that want iconic sci-fi campaigns and a lot of content in one package.", details:["Multiple co-op campaigns","Classic sci-fi story","Huge value package"], tags:["4 players","sci-fi","campaign","shooter","classic"] }),
  game({ title:"Gears 5", appId:"1097840", genre:"Cover Shooter", players:"3", platforms:"PC, Xbox", price:{eur:39.99,gbp:34.99}, rating:4.2, intensity:"high", story:"high", pace:"balanced", mood:"sci-fi", teamwork:"medium", gamePassPc:"included", vibe:"Cinematic cover shooting, campaign, Horde", description:"A polished third-person shooter with campaign co-op, Horde mode, and strong action set pieces.", whyPlay:"Pick it when you want a cinematic shooter campaign with chunky combat and extra co-op modes.", details:["Campaign co-op","Horde mode","Cinematic action"], tags:["3 players","shooter","story","sci-fi","horde"] }),
  game({ title:"Left 4 Dead 2", appId:"550", genre:"Zombie Shooter", players:"4", platforms:"PC, Xbox", price:{eur:9.75,gbp:8.50}, rating:4.8, story:"light", intensity:"high", pace:"fast", mood:"zombie", teamwork:"high", vibe:"Classic zombie campaigns, hordes, survival", description:"A timeless four-player zombie campaign shooter with great pacing, enemy variety, and replayability.", whyPlay:"Still one of the cleanest co-op designs ever: easy to understand, hard to master, and always tense.", details:["Four-player campaigns","AI Director pacing","Excellent replayability"], tags:["4 players","zombies","classic","shooter","horde"] }),
  game({ title:"Valheim", appId:"892970", genre:"Survival Adventure", players:"10", platforms:"PC, Xbox", price:{eur:19.99,gbp:16.75}, rating:4.6, story:"light", intensity:"medium", pace:"open", mood:"fantasy", teamwork:"high", gamePassPc:"included", vibe:"Vikings, survival, building, bosses", description:"A Viking survival sandbox about exploration, building, sailing, crafting, and defeating biome bosses.", whyPlay:"Excellent for bigger groups who want a shared world, long-term progression, and player-made stories.", details:["Large group co-op","Base building and sailing","Boss progression"], tags:["10 players","survival","crafting","open world","fantasy"] }),
  game({ title:"Payday 2", appId:"218620", genre:"Heist Shooter", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:9.99,gbp:7.99}, rating:4.3, story:"light", intensity:"high", pace:"fast", mood:"crime", teamwork:"high", vibe:"Heists, builds, stealth or loud", description:"A four-player heist shooter where crews can sneak, drill, shout, shoot, and escape with the money.", whyPlay:"Good for groups that want replayable missions, builds, and both stealth and loud approaches.", details:["Four-player heists","Stealth or loud options","Huge amount of content"], tags:["4 players","heist","shooter","crime","builds"] }),
  game({ title:"Ready or Not", appId:"1144200", genre:"Tactical Shooter", players:"5", platforms:"PC", price:{eur:49.99,gbp:44.99}, rating:4.2, intensity:"hard", pace:"tactical", mood:"military", teamwork:"high", vibe:"SWAT tactics, planning, realism", description:"A tense tactical shooter about careful room clearing, communication, and realistic squad execution.", whyPlay:"Choose this for serious tactical sessions where positioning, patience, and communication matter.", details:["Five-player tactical co-op","Realistic room clearing","High communication requirement"], tags:["5 players","tactical","shooter","realistic","teamwork"] }),
  game({ title:"No Man's Sky", appId:"275850", genre:"Space Survival", players:"4", platforms:"PC, PlayStation, Xbox, Switch", price:{eur:59.99,gbp:49.99}, rating:4.4, story:"medium", intensity:"light", pace:"open", mood:"sci-fi", teamwork:"medium", gamePassPc:"included", vibe:"Space exploration, base building, survival", description:"A huge space exploration sandbox with base building, expeditions, planets, ships, and relaxed co-op discovery.", whyPlay:"Great for a group that wants exploration and chill progression rather than nonstop combat.", details:["Co-op exploration","Base building","Huge procedural universe"], tags:["4 players","space","survival","open world","exploration"] }),
  game({ title:"Forza Horizon 5", appId:"1551360", genre:"Open-World Racing", players:"12", platforms:"PC, Xbox", price:{eur:59.99,gbp:54.99}, rating:4.6, story:"light", intensity:"light", pace:"open", mood:"racing", teamwork:"low", gamePassPc:"included", vibe:"Cars, open world, events, cruising", description:"A beautiful open-world racing game with convoy co-op, events, custom races, and casual driving sessions.", whyPlay:"Perfect if your group wants something relaxed, beautiful, and easy to jump into between heavier games.", details:["Convoy co-op","Open-world racing","Massive car list"], tags:["12 players","racing","open world","casual","game pass"] }),
  game({ title:"Warhammer 40,000: Darktide", appId:"1361210", genre:"Co-op Shooter", players:"4", platforms:"PC, Xbox", price:{eur:39.99,gbp:32.99}, rating:4.1, intensity:"high", pace:"fast", mood:"sci-fi", teamwork:"high", gamePassPc:"included", vibe:"40K hive city, guns, melee, hordes", description:"A grim sci-fi co-op horde shooter with brutal melee, guns, classes, and incredible atmosphere.", whyPlay:"Best if your squad wants a darker, heavier sci-fi version of co-op horde combat.", details:["Four-player missions","Melee and ranged combat","Strong atmosphere"], tags:["4 players","sci-fi","horde","shooter","melee"] }),
  game({ title:"Warhammer: Vermintide 2", appId:"552500", genre:"Melee Co-op Action", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:27.99,gbp:23.79}, rating:4.4, intensity:"high", pace:"fast", mood:"fantasy", teamwork:"high", vibe:"First-person melee, fantasy hordes", description:"A brutal first-person co-op melee game with hordes, classes, careers, loot, and dark fantasy atmosphere.", whyPlay:"Pick it when your group wants satisfying melee, clutch moments, and fantasy horde pressure.", details:["Four-player missions","Excellent melee combat","Multiple careers and builds"], tags:["4 players","fantasy","melee","horde","classes"] }),
  game({ title:"Risk of Rain 2", appId:"632360", genre:"Roguelike Action", players:"4", platforms:"PC, PlayStation, Xbox, Switch", price:{eur:24.99,gbp:19.49}, rating:4.6, story:"light", intensity:"high", pace:"fast", mood:"sci-fi", teamwork:"medium", vibe:"Roguelike runs, scaling chaos, loot", description:"A run-based third-person roguelike where items stack into ridiculous builds and the difficulty keeps climbing.", whyPlay:"Great for repeat sessions, wild builds, and groups that like escalating chaos over scripted story.", details:["Four-player online co-op","Roguelike item builds","Highly replayable"], tags:["4 players","roguelike","sci-fi","loot","chaos"] }),
  game({ title:"Phasmophobia", appId:"739630", genre:"Co-op Horror", players:"4", platforms:"PC", price:{eur:19.50,gbp:16.75}, rating:4.5, story:"light", intensity:"medium", pace:"tactical", mood:"horror", teamwork:"high", vibe:"Ghost hunting, investigation, proximity voice", description:"A four-player ghost investigation game where communication, fear, and evidence gathering create memorable sessions.", whyPlay:"Great for groups that want tension, laughs, and spooky teamwork without a long campaign commitment.", details:["Four-player investigations","Voice-based tension","High replayability"], tags:["4 players","horror","investigation","teamwork","ghosts"] }),
  game({ title:"GTFO", appId:"493520", genre:"Hardcore Co-op Shooter", players:"4", platforms:"PC", price:{eur:39.99,gbp:34.99}, rating:4.2, intensity:"hard", pace:"tactical", mood:"horror", teamwork:"high", vibe:"Stealth, horror, hardcore teamwork", description:"A brutally difficult co-op shooter that demands planning, communication, stealth, and precise execution.", whyPlay:"Only pick this if your group wants serious challenge and does not mind failing until the plan works.", details:["Four-player hardcore missions","Very high coordination requirement","Stealth and resource pressure"], tags:["4 players","hardcore","horror","tactical","shooter"] }),
  game({ title:"Dying Light 2 Stay Human", appId:"534380", genre:"Open-World Zombie Action", players:"4", platforms:"PC, PlayStation, Xbox", price:{eur:59.99,gbp:54.99}, rating:4.1, intensity:"high", pace:"open", mood:"zombie", vibe:"Parkour, zombies, city exploration", description:"A zombie parkour action game with a co-op open world, melee combat, and tense night exploration.", whyPlay:"Best when your squad wants movement, rooftops, melee fights, and zombie chaos in an open city.", details:["Four-player online co-op","Parkour exploration","Nighttime danger"], tags:["4 players","zombies","open world","parkour","action"] }),
  game({ title:"Dead Island 2", appId:"934700", genre:"Zombie Action", players:"3", platforms:"PC, PlayStation, Xbox", price:{eur:59.99,gbp:54.99}, rating:4.0, intensity:"high", pace:"fast", mood:"zombie", vibe:"Gory zombie action, LA, melee", description:"A flashy zombie brawler with co-op, gore-heavy melee combat, and a lighter horror-comedy tone.", whyPlay:"Pick this for simple, satisfying zombie destruction with great visuals and quick co-op fun.", details:["Three-player online co-op","Gory melee system","Easy to jump into"], tags:["3 players","zombies","melee","action","gore"] }),
  game({ title:"Castle Crashers", appId:"204360", genre:"Beat 'em Up", players:"4", platforms:"PC, PlayStation, Xbox, Switch", price:{eur:14.99,gbp:11.99}, rating:4.5, story:"light", intensity:"light", pace:"fast", mood:"comedy", teamwork:"medium", vibe:"Arcade brawler, jokes, chaos", description:"A colorful four-player beat 'em up with simple fun, silly humor, leveling, and couch co-op energy.", whyPlay:"Perfect for casual nights when you want quick laughs, button-mashing, and low-friction co-op.", details:["Four-player brawling","Easy to pick up","Great couch co-op feel"], tags:["4 players","brawler","comedy","casual","couch co-op"] }),
  game({ title:"TMNT: Shredder's Revenge", appId:"1361510", genre:"Beat 'em Up", players:"6", platforms:"PC, PlayStation, Xbox, Switch", price:{eur:24.99,gbp:22.49}, rating:4.4, story:"light", intensity:"light", pace:"fast", mood:"arcade", teamwork:"medium", vibe:"Arcade action, turtles, couch chaos", description:"A polished arcade brawler with six-player chaos, great pixel art, and fast co-op action.", whyPlay:"Great when you want an easy, stylish arcade game that almost anyone can jump into.", details:["Up to six players","Arcade beat 'em up","Short session friendly"], tags:["6 players","arcade","brawler","casual","couch co-op"] }),
  game({ title:"Unravel Two", appId:"1225570", genre:"Puzzle Platformer", players:"2", platforms:"PC, PlayStation, Xbox, Switch", price:{eur:19.99,gbp:17.99}, rating:4.3, story:"medium", intensity:"light", pace:"balanced", mood:"adventure", teamwork:"high", gamePassPc:"included", vibe:"Beautiful puzzle platforming, two yarn characters", description:"A gentle and beautiful two-player puzzle platformer about movement, timing, and helping each other forward.", whyPlay:"Great for a calmer co-op night with lovely visuals, teamwork, and low stress.", details:["Two-player puzzle platforming","Beautiful art direction","Good for casual duos"], tags:["2 players","puzzle","platformer","casual","teamwork"] }),
  game({ title:"Cuphead", appId:"268910", genre:"Run & Gun", players:"2", platforms:"PC, PlayStation, Xbox, Switch", price:{eur:19.99,gbp:16.99}, rating:4.6, story:"light", intensity:"hard", pace:"fast", mood:"arcade", teamwork:"medium", vibe:"Boss rush, cartoons, hard co-op", description:"A beautiful but punishing run-and-gun boss rush inspired by classic animation.", whyPlay:"Pick it if your duo wants challenge, style, and a lot of shouting at boss patterns.", details:["Two-player co-op","Very hard boss fights","Outstanding art style"], tags:["2 players","bosses","hard","arcade","platformer"] })
];

const featuredShortlist = ["Dying Light: The Beast", "Tom Clancy's The Division 2", "Destiny 2", "Borderlands 4", "FINAL FANTASY XIV Online"];
const shortlistGames = featuredShortlist;
