const games = [
  {
    title: "Darksiders Genesis",
    genre: "Action-Adventure",
    players: "2",
    platforms: "PC, PlayStation, Xbox, Switch",
    vibe: "Comic-book fantasy, boss fights, campaign co-op",
    rating: 4.5,
    intensity: "medium",
    story: "medium",
    pace: "balanced",
    mood: "fantasy",
    teamwork: "high",
    description: "An underrated two-player action adventure with a full campaign, punchy combat, bosses, and strong buddy-game energy.",
    tags: ["2 players", "story", "boss fights", "action", "fantasy"]
  },
  {
    title: "Sniper Elite 5",
    genre: "Tactical Shooter",
    players: "2",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Stealth, open missions, campaign co-op",
    rating: 4.3,
    intensity: "medium",
    story: "medium",
    pace: "tactical",
    mood: "military",
    teamwork: "high",
    description: "A full co-op campaign built around planning, stealth, synchronized shots, and chaotic fallback plans when everything goes wrong.",
    tags: ["2 players", "shooter", "stealth", "campaign", "tactical"]
  },
  {
    title: "Ghost Recon Wildlands",
    genre: "Open-World Shooter",
    players: "4",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Cartel story, tactics, vehicles, chaos",
    rating: 4.4,
    intensity: "medium",
    story: "medium",
    pace: "open",
    mood: "military",
    teamwork: "high",
    description: "A flexible open-world co-op campaign where your squad can sneak, snipe, drive, fly, or turn every mission into complete chaos.",
    tags: ["4 players", "open world", "tactical", "shooter", "vehicles"]
  },
  {
    title: "The Ascent",
    genre: "Cyberpunk Shooter",
    players: "4",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Twin-stick combat, neon cities, loot, worldbuilding",
    rating: 4.1,
    intensity: "high",
    story: "medium",
    pace: "fast",
    mood: "sci-fi",
    teamwork: "medium",
    description: "A stylish cyberpunk shooter with dense atmosphere, heavy firefights, loot, and a strong sense of place.",
    tags: ["4 players", "cyberpunk", "loot", "action", "sci-fi"]
  },
  {
    title: "Outriders",
    genre: "Looter Shooter",
    players: "3",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Classes, abilities, story campaign, grind",
    rating: 4.0,
    intensity: "high",
    story: "medium",
    pace: "fast",
    mood: "sci-fi",
    teamwork: "medium",
    description: "A loud three-player power-fantasy shooter for groups that like classes, abilities, builds, loot, and aggressive combat.",
    tags: ["3 players", "loot", "abilities", "story", "shooter"]
  },
  {
    title: "Strange Brigade",
    genre: "Adventure Shooter",
    players: "4",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Pulp adventure, mummies, traps, puzzles",
    rating: 4.0,
    intensity: "medium",
    story: "light",
    pace: "balanced",
    mood: "pulp",
    teamwork: "medium",
    description: "A pulpy co-op shooter with monster waves, traps, light puzzles, and the energy of a chaotic adventure serial.",
    tags: ["4 players", "pulp", "puzzles", "shooter", "monsters"]
  },
  {
    title: "Evil West",
    genre: "Action Brawler",
    players: "2",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Cowboys, vampires, melee combat, escalation",
    rating: 4.0,
    intensity: "high",
    story: "light",
    pace: "fast",
    mood: "monster",
    teamwork: "medium",
    description: "A compact monster-bashing action game with heavy hits, stylish combat, and wonderfully trashy vampire western energy.",
    tags: ["2 players", "brawler", "monsters", "action", "western"]
  },
  {
    title: "Nioh 2",
    genre: "Soulslike",
    players: "3",
    platforms: "PC, PlayStation",
    vibe: "Hard fights, loot, bosses, samurai fantasy",
    rating: 4.6,
    intensity: "hard",
    story: "medium",
    pace: "tactical",
    mood: "fantasy",
    teamwork: "high",
    description: "A demanding action RPG with deep builds, intense boss fights, loot, and very rewarding co-op for patient groups.",
    tags: ["3 players", "soulslike", "boss fights", "loot", "hard"]
  },
  {
    title: "Wo Long: Fallen Dynasty",
    genre: "Action RPG",
    players: "3",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Parries, fast combat, Three Kingdoms fantasy",
    rating: 4.1,
    intensity: "hard",
    story: "medium",
    pace: "fast",
    mood: "fantasy",
    teamwork: "medium",
    description: "A faster, parry-heavy action RPG that rewards timing, aggression, and groups that enjoy boss-focused combat.",
    tags: ["3 players", "parry", "action RPG", "bosses", "hard"]
  },
  {
    title: "Aliens: Fireteam Elite",
    genre: "Co-op Shooter",
    players: "3",
    platforms: "PC, PlayStation, Xbox, Switch",
    vibe: "Aliens, classes, hordes, missions",
    rating: 3.9,
    intensity: "high",
    story: "light",
    pace: "fast",
    mood: "sci-fi",
    teamwork: "high",
    description: "A mission-based squad shooter with Aliens atmosphere, class synergy, horde pressure, and clean three-player co-op structure.",
    tags: ["3 players", "sci-fi", "horde", "shooter", "classes"]
  },
  {
    title: "Lara Croft and the Guardian of Light",
    genre: "Action Puzzle",
    players: "2",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Puzzles, temples, teamwork, compact adventure",
    rating: 4.2,
    intensity: "light",
    story: "light",
    pace: "balanced",
    mood: "adventure",
    teamwork: "high",
    description: "A compact co-op adventure with a strong mix of combat, puzzles, platforming, and actual teamwork moments.",
    tags: ["2 players", "puzzles", "adventure", "couch co-op", "teamwork"]
  },
  {
    title: "Code Vein",
    genre: "Anime Soulslike",
    players: "2",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Anime, dark world, builds, bosses",
    rating: 3.9,
    intensity: "hard",
    story: "high",
    pace: "tactical",
    mood: "anime",
    teamwork: "medium",
    description: "A dark anime soulslike with more story presentation than many genre peers, build variety, and co-op boss runs.",
    tags: ["2 players", "soulslike", "anime", "story", "bosses"]
  }
];

const shortlistGames = [
  "Nioh 2",
  "Ghost Recon Wildlands",
  "Darksiders Genesis",
  "Sniper Elite 5",
  "The Ascent"
];
