const games = [
  {
    title: "Darksiders Genesis",
    genre: "Action-Adventure",
    players: "2",
    platforms: "PC, PlayStation, Xbox, Switch",
    vibe: "Comic-book fantasy, boss fights, campaign co-op",
    rating: 4.5,
    intensity: "medium",
    story: "medium",
    pace: "balanced",
    mood: "fantasy",
    teamwork: "high",
    price: { eur: 29.99, gbp: 24.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/710920/header.jpg",
    trailerQuery: "Darksiders Genesis official trailer",
    storeUrl: "https://store.steampowered.com/app/710920/Darksiders_Genesis/",
    whyPlay: "Best if you want a stylish two-player campaign that feels like an arcade action adventure instead of another generic looter.",
    details: ["Full campaign co-op", "Two distinct characters", "Great for boss-focused sessions"],
    description: "An underrated two-player action adventure with a full campaign, punchy combat, bosses, and strong buddy-game energy.",
    tags: ["2 players", "story", "boss fights", "action", "fantasy"]
  },
  {
    title: "Sniper Elite 5",
    genre: "Tactical Shooter",
    players: "2",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Stealth, open missions, campaign co-op",
    rating: 4.3,
    intensity: "medium",
    story: "medium",
    pace: "tactical",
    mood: "military",
    teamwork: "high",
    price: { eur: 49.99, gbp: 44.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1029690/header.jpg",
    trailerQuery: "Sniper Elite 5 official trailer",
    storeUrl: "https://store.steampowered.com/app/1029690/Sniper_Elite_5/",
    whyPlay: "Perfect for duos who like planning, patience, stealth kills, and that one inevitable moment where the whole map turns hostile.",
    details: ["Full campaign in co-op", "Large stealth sandboxes", "Great tactical replay value"],
    description: "A full co-op campaign built around planning, stealth, synchronized shots, and chaotic fallback plans when everything goes wrong.",
    tags: ["2 players", "shooter", "stealth", "campaign", "tactical"]
  },
  {
    title: "Ghost Recon Wildlands",
    genre: "Open-World Shooter",
    players: "4",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Cartel story, tactics, vehicles, chaos",
    rating: 4.4,
    intensity: "medium",
    story: "medium",
    pace: "open",
    mood: "military",
    teamwork: "high",
    price: { eur: 49.99, gbp: 42.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/460930/header.jpg",
    trailerQuery: "Ghost Recon Wildlands official trailer",
    storeUrl: "https://store.steampowered.com/app/460930/Tom_Clancys_Ghost_Recon_Wildlands/",
    whyPlay: "The best pick for squads that want freedom: sneak in, fly out, crash vehicles, sync-shot enemies, or create absolute chaos.",
    details: ["Four-player open-world co-op", "Vehicles and helicopters", "Stealth or loud approaches"],
    description: "A flexible open-world co-op campaign where your squad can sneak, snipe, drive, fly, or turn every mission into complete chaos.",
    tags: ["4 players", "open world", "tactical", "shooter", "vehicles"]
  },
  {
    title: "The Ascent",
    genre: "Cyberpunk Shooter",
    players: "4",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Twin-stick combat, neon cities, loot, worldbuilding",
    rating: 4.1,
    intensity: "high",
    story: "medium",
    pace: "fast",
    mood: "sci-fi",
    teamwork: "medium",
    price: { eur: 29.99, gbp: 24.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/979690/header.jpg",
    trailerQuery: "The Ascent official trailer",
    storeUrl: "https://store.steampowered.com/app/979690/The_Ascent/",
    whyPlay: "A strong choice if your group wants neon style, heavy firefights, upgrades, and a world that looks expensive without needing a huge commitment.",
    details: ["Up to four-player co-op", "Beautiful cyberpunk world", "Fast twin-stick firefights"],
    description: "A stylish cyberpunk shooter with dense atmosphere, heavy firefights, loot, and a strong sense of place.",
    tags: ["4 players", "cyberpunk", "loot", "action", "sci-fi"]
  },
  {
    title: "Outriders",
    genre: "Looter Shooter",
    players: "3",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Classes, abilities, story campaign, grind",
    rating: 4.0,
    intensity: "high",
    story: "medium",
    pace: "fast",
    mood: "sci-fi",
    teamwork: "medium",
    price: { eur: 39.99, gbp: 34.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/680420/header.jpg",
    trailerQuery: "Outriders official trailer",
    storeUrl: "https://store.steampowered.com/app/680420/OUTRIDERS/",
    whyPlay: "Good for three players who want abilities, classes, aggressive shooting, and a campaign that keeps pushing loot and builds forward.",
    details: ["Three-player co-op", "Class-based powers", "Loot and build crafting"],
    description: "A loud three-player power-fantasy shooter for groups that like classes, abilities, builds, loot, and aggressive combat.",
    tags: ["3 players", "loot", "abilities", "story", "shooter"]
  },
  {
    title: "Strange Brigade",
    genre: "Adventure Shooter",
    players: "4",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Pulp adventure, mummies, traps, puzzles",
    rating: 4.0,
    intensity: "medium",
    story: "light",
    pace: "balanced",
    mood: "pulp",
    teamwork: "medium",
    price: { eur: 49.99, gbp: 39.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/312670/header.jpg",
    trailerQuery: "Strange Brigade official trailer",
    storeUrl: "https://store.steampowered.com/app/312670/Strange_Brigade/",
    whyPlay: "A fun choice when you want pulpy adventure, monsters, traps, and casual four-player chaos without needing deep systems.",
    details: ["Four-player missions", "Pulp adventure tone", "Light puzzles and traps"],
    description: "A pulpy co-op shooter with monster waves, traps, light puzzles, and the energy of a chaotic adventure serial.",
    tags: ["4 players", "pulp", "puzzles", "shooter", "monsters"]
  },
  {
    title: "Evil West",
    genre: "Action Brawler",
    players: "2",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Cowboys, vampires, melee combat, escalation",
    rating: 4.0,
    intensity: "high",
    story: "light",
    pace: "fast",
    mood: "monster",
    teamwork: "medium",
    price: { eur: 49.99, gbp: 44.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1065310/header.jpg",
    trailerQuery: "Evil West official trailer",
    storeUrl: "https://store.steampowered.com/app/1065310/Evil_West/",
    whyPlay: "Pick this for loud monster punching, cowboy vampire nonsense, and quick action that does not overcomplicate game night.",
    details: ["Two-player online co-op", "Heavy melee and gun combos", "Trashy monster-western story"],
    description: "A compact monster-bashing action game with heavy hits, stylish combat, and wonderfully trashy vampire western energy.",
    tags: ["2 players", "brawler", "monsters", "action", "western"]
  },
  {
    title: "Nioh 2",
    genre: "Soulslike",
    players: "3",
    platforms: "PC, PlayStation",
    vibe: "Hard fights, loot, bosses, samurai fantasy",
    rating: 4.6,
    intensity: "hard",
    story: "medium",
    pace: "tactical",
    mood: "fantasy",
    teamwork: "high",
    price: { eur: 49.99, gbp: 39.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1325200/header.jpg",
    trailerQuery: "Nioh 2 complete edition official trailer",
    storeUrl: "https://store.steampowered.com/app/1325200/Nioh_2__The_Complete_Edition/",
    whyPlay: "The hardest recommendation here. Great if your group wants boss fights, loot, build depth, and the satisfaction of finally winning.",
    details: ["Up to three-player expeditions", "Deep build system", "Demanding boss fights"],
    description: "A demanding action RPG with deep builds, intense boss fights, loot, and very rewarding co-op for patient groups.",
    tags: ["3 players", "soulslike", "boss fights", "loot", "hard"]
  },
  {
    title: "Wo Long: Fallen Dynasty",
    genre: "Action RPG",
    players: "3",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Parries, fast combat, Three Kingdoms fantasy",
    rating: 4.1,
    intensity: "hard",
    story: "medium",
    pace: "fast",
    mood: "fantasy",
    teamwork: "medium",
    price: { eur: 59.99, gbp: 54.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1448440/header.jpg",
    trailerQuery: "Wo Long Fallen Dynasty official trailer",
    storeUrl: "https://store.steampowered.com/app/1448440/Wo_Long_Fallen_Dynasty/",
    whyPlay: "For groups that want a faster, parry-heavy action RPG and do not mind getting punished until the timing clicks.",
    details: ["Three-player co-op", "Parry-focused combat", "Boss-heavy missions"],
    description: "A faster, parry-heavy action RPG that rewards timing, aggression, and groups that enjoy boss-focused combat.",
    tags: ["3 players", "parry", "action RPG", "bosses", "hard"]
  },
  {
    title: "Aliens: Fireteam Elite",
    genre: "Co-op Shooter",
    players: "3",
    platforms: "PC, PlayStation, Xbox, Switch",
    vibe: "Aliens, classes, hordes, missions",
    rating: 3.9,
    intensity: "high",
    story: "light",
    pace: "fast",
    mood: "sci-fi",
    teamwork: "high",
    price: { eur: 29.99, gbp: 24.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1549970/header.jpg",
    trailerQuery: "Aliens Fireteam Elite official trailer",
    storeUrl: "https://store.steampowered.com/app/1549970/Aliens_Fireteam_Elite/",
    whyPlay: "Best when you want clean mission structure, alien swarms, classes, and quick squad shooting without a huge learning curve.",
    details: ["Three-player squad missions", "Class synergy", "Horde pressure"],
    description: "A mission-based squad shooter with Aliens atmosphere, class synergy, horde pressure, and clean three-player co-op structure.",
    tags: ["3 players", "sci-fi", "horde", "shooter", "classes"]
  },
  {
    title: "Lara Croft and the Guardian of Light",
    genre: "Action Puzzle",
    players: "2",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Puzzles, temples, teamwork, compact adventure",
    rating: 4.2,
    intensity: "light",
    story: "light",
    pace: "balanced",
    mood: "adventure",
    teamwork: "high",
    price: { eur: 9.99, gbp: 6.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/35130/header.jpg",
    trailerQuery: "Lara Croft and the Guardian of Light trailer",
    storeUrl: "https://store.steampowered.com/app/35130/Lara_Croft_and_the_Guardian_of_Light/",
    whyPlay: "A compact pick for duos who want actual co-op puzzle solving instead of simply shooting enemies next to each other.",
    details: ["Two-player puzzle action", "Great teamwork moments", "Shorter and easy to recommend"],
    description: "A compact co-op adventure with a strong mix of combat, puzzles, platforming, and actual teamwork moments.",
    tags: ["2 players", "puzzles", "adventure", "couch co-op", "teamwork"]
  },
  {
    title: "Code Vein",
    genre: "Anime Soulslike",
    players: "2",
    platforms: "PC, PlayStation, Xbox",
    vibe: "Anime, dark world, builds, bosses",
    rating: 3.9,
    intensity: "hard",
    story: "high",
    pace: "tactical",
    mood: "anime",
    teamwork: "medium",
    price: { eur: 49.99, gbp: 39.99 },
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/678960/header.jpg",
    trailerQuery: "Code Vein official trailer",
    storeUrl: "https://store.steampowered.com/app/678960/CODE_VEIN/",
    whyPlay: "A strong anime-styled option if you want soulslike bosses but also more character-driven presentation than most games in the genre.",
    details: ["Two-player boss runs", "Anime story presentation", "Build variety"],
    description: "A dark anime soulslike with more story presentation than many genre peers, build variety, and co-op boss runs.",
    tags: ["2 players", "soulslike", "anime", "story", "bosses"]
  }
];

const shortlistGames = ["Nioh 2", "Ghost Recon Wildlands", "Darksiders Genesis", "Sniper Elite 5", "The Ascent"];
